name: Build and Deploy Antora Site

on:
  push:
    branches:
      - main  # adjust this if your primary branch is named differently

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install rsync, zopfli and brotli
      run: sudo apt-get install -y rsync brotli zopfli

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Antora is known to work well with this version, but you can adjust as needed

    - name: Install Antora
      run: |
        npm install -g antora

    - name: Build the Antora site
      run: |
        antora --fetch antora-playbook.yml  # Replace 'antora-playbook.yml' with your playbook's name if different

    - name: Install PurgeCSS
      run: |
        npm install -g purgecss

    - name: Replace paths in CSS files using awk
      run: |
        awk '{gsub(/url\(..\//, "url(/antora-assets/"); print}' ./build/site/antora-assets/css/site.css > ./build/site/antora-assets/css/site_temp.css && mv ./build/site/antora-assets/css/site_temp.css ./build/site/antora-assets/css/site.css
        awk '{gsub(/url\(..\//, "url(/antora-assets/"); print}' ./build/site/antora-assets/css/site-extra.css > ./build/site/antora-assets/css/site-extra_temp.css && mv ./build/site/antora-assets/css/site-extra_temp.css ./build/site/antora-assets/css/site-extra.css

    - name: Optimize and Inline CSS for each HTML file
      run: |
        WHITELIST_CLASSES=".toc {} .embedded {} .toc-menu {}"

        find ./build/site/ -name "*.html" | while read -r file; do
          # Append whitelisted classes to the CSS files
          echo "$WHITELIST_CLASSES" >> ./build/site/antora-assets/css/site.css
          echo "$WHITELIST_CLASSES" >> ./build/site/antora-assets/css/site-extra.css

          # Optimize CSS for the current HTML file
          purgecss --content "$file" --css ./build/site/antora-assets/css/site.css --output ./build/site/antora-assets/css/site_temp.css
          purgecss --content "$file" --css ./build/site/antora-assets/css/site-extra.css --output ./build/site/antora-assets/css/site-extra_temp.css

          # Combine the optimized CSS files
          SITE_CSS=$(cat ./build/site/antora-assets/css/site_temp.css)
          SITE_EXTRA_CSS=$(cat ./build/site/antora-assets/css/site-extra_temp.css)
          COMBINED_CSS="$SITE_CSS $SITE_EXTRA_CSS"

          # Inline the combined optimized CSS into the current HTML file
          awk -v css="$COMBINED_CSS" '/<head>/ {print; print "<style>" css "</style>"; next} 1' "$file" > "$file".tmp && mv "$file".tmp "$file"

          # Remove the original link tags from the current HTML file
          sed -i "/antora-assets\/css\/site.css/d" "$file"
          sed -i "/antora-assets\/css\/site-extra.css/d" "$file"

          # Clean up temporary CSS files
          rm ./build/site/antora-assets/css/site_temp.css
          rm ./build/site/antora-assets/css/site-extra_temp.css
        done



    # - name: Install clean-css-cli
    #   run: |
    #     npm install -g clean-css-cli

    # - name: Minify CSS files
    #   run: |
    #     cleancss -o ./build/site/antora-assets/css/site.css ./build/site/antora-assets/css/site.css
    #     cleancss -o ./build/site/antora-assets/css/site-extra.css ./build/site/antora-assets/css/site-extra.css

    # - name: Inline CSS and remove original link tags
    #   run: |
    #     SITE_CSS=$(cat ./build/site/antora-assets/css/site.css)
    #     SITE_EXTRA_CSS=$(cat ./build/site/antora-assets/css/site-extra.css)
    #     COMBINED_CSS="$SITE_CSS $SITE_EXTRA_CSS"
    #     find ./build/site/ -name "*.html" | while read -r file; do
    #       # Use awk to insert the CSS content after the <head> tag
    #       awk -v css="$COMBINED_CSS" '/<head>/ {print; print "<style>" css "</style>"; next} 1' "$file" > "$file".tmp && mv "$file".tmp "$file"
    #       # Remove the original link tags
    #       sed -i "/antora-assets\/css\/site.css/d" "$file"
    #       sed -i "/antora-assets\/css\/site-extra.css/d" "$file"
    #     done

    # - name: Install html-minifier
    #   run: |
    #     npm install -g html-minifier

    # - name: Aggressively minify HTML files
    #   run: |
    #     find ./build/site/ -name "*.html" | while read -r file; do
    #       html-minifier --collapse-whitespace --remove-comments --minify-js --minify-css --remove-redundant-attributes --remove-script-type-attributes --remove-style-link-type-attributes --use-short-doctype --collapse-boolean-attributes --sort-attributes --sort-class-name < "$file" > "$file".tmp
    #       mv "$file".tmp "$file"
    #     done

    # - name: Zopfli compress all HTML and CSS files
    #   run: |
    #       find ./build/site/ \( -name "*.html" -o -name "*.css" \) -exec zopfli --i20 {} \;

    # - name: Brotli compress all HTML and CSS files
    #   run: |
    #     find ./build/site/ \( -name "*.html" -o -name "*.css" \) -exec brotli {} \;

    - name: Deploy to Linux server via rsync
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
        SERVER: ${{ secrets.SERVER_ADDRESS }}
        USERNAME: ${{ secrets.SERVER_USERNAME }}
        TARGET: ${{ secrets.SERVER_TARGET_DIRECTORY }}
        KNOWN_HOSTS: ${{ secrets.KNOWN_HOSTS_ENTRY }}
      run: |
        echo "$DEPLOY_KEY" > deploy_key
        chmod 600 deploy_key
        echo "$KNOWN_HOSTS" > known_hosts
        rsync -avz -e 'ssh -i deploy_key -o UserKnownHostsFile=known_hosts' --delete ./build/site/ $USERNAME@$SERVER:$TARGET
        rm -f deploy_key known_hosts
